### ISSUE TITLE
Open Bot using FullScreen URL causes "Could not display component" error

### ISSUE THREAD

**Issue by GChester** [botpress/v12#1050]
**Describe the bug**
After doing a search there seems to be lots of problems with this and I'm a bit surprised it has not been solved by now, but when you try to open the Chatbot in fullscreen it errors with the following error;

```
Could not display component
An error occurred while loading the component
Cannot read property 'stylesheet' of undefined

Developer? click here to see why this might happen
```

**To Reproduce**
1. Go to http://domain.com:3000/lite/botid/?m=channel-web&v=Fullscreen
2. See error

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 83
 - Botpress Version 12.10.2

![image](https://user-images.githubusercontent.com/3395933/86132567-a250c400-bb19-11ea-962d-9599ac32d9f5.png)

**Comment by Vinici0** [comment]
Igual no me funciona, alguien tiene una solucion?
