### ISSUE TITLE
[BUG] Emulator button not working past 12_14_2 (Docker-based setup)

### ISSUE THREAD

**Issue by kulemantu** [botpress/v12#1182]
**Describe the bug**
Upgrading my Dockerfile to pull from 12_14_0 to 12_15_2 broke the Emulator button on the top right

**To Reproduce**
Steps to reproduce the behaviour:

1. Install Botpress via Docker with botpres_data and botpress_lang using local folders
2. Set up your initial Botpress account
3. Create a bot & a node (or use an existing bot; same result)
4. Click on the Emulator button on the top right
5. The emulator does not appear from the right side of the browser as expected

**Expected behaviour**
Expected emulator to appear from the right side

**Screenshots**
Whole page
![image](https://user-images.githubusercontent.com/907164/101611450-95b28f00-3a1a-11eb-8ab9-8be8c14e7978.png)

Console Error
![image](https://user-images.githubusercontent.com/907164/101611766-f6da6280-3a1a-11eb-9477-6b6fb0858168.png)

**Environment (please complete the following information):**

- OS: Ubuntu 20
- Browser: Google Chrome & Safari
- Browser Version: (Chrome Version 87.0.4280.88 (Official Build) (x86_64)) (Safari Version 14.0.1 (15610.2.11.51.10, 15610))
- Botpress Version: 12.14.2, 12.15.0
- NodeJS: Botpress Docker Node

**Additional context**
- Problem happens for new bots and old bots
- This was a vanilla install of Botpress on Ubuntu 20 + 12.14.2, the older install was working on Ubuntu 18 + 12.4.0, couldn't test for that OS & version as the older installation was deleted

**Comment by danellereneau** [comment]
I'm having a similar issue with the Emulator.. It's minimized and can't open it.
![Emulator](https://github.com/botpress/v12/assets/147838656/d991ab9e-b502-4299-bb23-58b6e2ce8748)
