### ISSUE TITLE
Clear chat history on page refresh

### ISSUE THREAD

**Issue by makotobits** [botpress/v12#1505]
It is a optional behaviour one would expect from a chatbot, having to be a developer or coder to implement this functionality into one chatbots.

The solution would be that on a page refresh it generates a new UserID so it shows a new chat.

Another alternative is that with a button on the chatbox, the user could hide the previous conversation.

**Comment by CMara14** [comment]
Tried to implement the exposeStore prop in true in the configuration but it gives me console errors

**Comment by hugsbrugs** [comment]
It seems from documentation : [https://botpress.com/docs/cloud/channels/webchat/setting-up-the-webchat/](https://botpress.com/docs/cloud/channels/webchat/setting-up-the-webchat/) that variable **exposeStore** does not exist any more ... so calling 
`window.botpressWebChat.store.resetConversation();`
throws an error in browser console.

I've tried to add `"useSessionStorage": true` in my init function but when reloading the page, the old conversation is still in chat history ...
