### ISSUE TITLE
Bot is using Languages not supported by NLU 

### ISSUE THREAD

**Issue by EduardoYapsi** [botpress/v12#1686]
**Describe the bug**
Im using the binary version of botpress, the thing is whether i import an already built bot or create a new one botpress instantly gives me the message that this lenguage is not supported by NLU. 
Im working with a bot that doesnt use NLU and when i open it with botpress app it opens normally.
Also another error appears at my screen:
       Request failed with status code 404

**To Reproduce**
Start Botpress binary version 12.30.2 create or import a new bot to the software

**Expected behavior**
A normal bootup of the software

**Screenshots**
![image](https://user-images.githubusercontent.com/99515171/191610219-0047503c-096f-456a-984a-2e4c5f0e5229.png)

**Environment (please complete the following information):**

- OS: Windows
- Browser: Edge
- Browser Version: 105.0.1343.42
- Botpress Version: 12.30.2
- NodeJS: 16.17.0

**Comment by yaya2devops** [comment]
@davidvitora You really feel you can close stuff with this ?
