### ISSUE TITLE
blank page white page grey page chat bot window and emulator botpress error page not displaying

### ISSUE THREAD

**Issue by securehosting1** [botpress/v12#1705]
**Describe the bug**
Blank page when i open a chat window for any chat bot i create.

**To Reproduce**

1.  make a ubuntu 20 vps server (NO DOCKER)  ( Using a large cloud VPS KVM )
2. follow this tutorial i made:
https://github.com/botpress/botpress/discussions/12393
4. open the chat bot chat after creating a chat bot
5. you will see a blank white page, and also emulator is blank too.

**Expected behaviour**
no blank page and able to see data that should be displayed like that chat.
**Error Screenshots**
![2022-12-07_00-13](https://user-images.githubusercontent.com/116322650/206326631-25e4c7c6-cc55-40dc-8039-9b2de574319d.png)

**Environment (please complete the following information):**

- OS: Ubuntu 20 64bit 
- Browser Chrome

- Botpress Version [ 12.30.5 ] and now also the same issue on [ 12.30.6 ]

**Additional context**
I have reinstalled 7 times this is not an issue on my side?

i followed this https://online-business-seo-forum.seotraining1.com/discussion/129/install-setup-ai-chat-bot-simple-easy-methods-using-botpress-or-rasa-full-info/p1?new=1 see that page it is exactly what i have done, also i have added fixes to issues that may happen.

Also, i get signed out after a while, i think may of edited and forgot, i edited the bits below:

Code Editor using web ui (admin area website where botpress is installed)  To make the external url work i added the domain below, should i change localhost to example.domain.com ? Last time i edited the file wrongly i had to reinstall the server. Editing from ssh command line does not work for me and does not apply changes but no issues saving changes etc, even after rebooting and starting services a few times.

botpress.config.json

Currently settings:

{
"$schema": "bp://types/botpress.config.schema.json",
"httpServer": {
"host": "localhost",
"port": 3000,
"backlog": 0,
"bodyLimit": "10mb",
"cors": {
"enabled": true
},
"externalUrl": "https://bridge.talktoai.online/",
"session": {
"enabled": false,
"maxAge": "1h"
},
"socketTransports": [
"websocket",
"polling"
],
"rateLimit": {
"enabled": false,
"limitWindow": "30s",
"limit": 600
},
"headers": {
"X-Powered-By": "Botpress"
}
},
"dialog": {
"janitorInterval": "10s",
"timeoutInterval": "25m",
"sessionTimeoutInterval": "30m"
},
"logs": {
"dbOutput": {
"expiration": "2 weeks",
"janitorInterval": "30s"
},
"fileOutput": {
"enabled": false,
"folder": "./",
"maxFileSize": 10000
}
},

My only big issue now is blank white page for the bot urt but the ssl is showing url is correct now. Emulator also displays no data blank grey.
Maybe i should change localhost to exmaple.domain.com

nginx.conf

                                                    /etc/nginx/nginx.conf     

                                                              
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}
http {
   upstream botpress-cluster {
       server localhost:3000;
   }
   server_tokens off;
   add_header X-Content-Type-Options nosniff;
   add_header X-XSS-Protection "1; mode=block";
   client_max_body_size 25M;
        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
# 
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}

 /etc/nginx/sites-enabled/chat.talktoai.online          

                                             
server {
   # listen on port 9443 (https)
    listen 80;
    server_name chat.talktoai.online MYSERVERIP;

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:3000;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chat.talktoai.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat.talktoai.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

**Comment by shaxiaozz** [comment]
@ResearchForumOnline Could you please share your nginx configuration? I have the same problem as you.

**Comment by shaxiaozz** [comment]
I think I found the problem. I connected the domain name to CloudFlare. After I unconnected to CloudFlare, the website returned to normal~
