### ISSUE TITLE
Links are not stored properly in the variables

### ISSUE THREAD

**Issue by bakrianoo** [botpress/v12#1808]
**Describe the bug**
I am trying to store a link in a variable, and then using it again to create a link button. The link to which the user is redirected to is invalid.

**To Reproduce**
Create an action to store a variable
Create a node to replace the variable value as a URL.

**Screenshots**
![image](https://github.com/botpress/v12/assets/14326057/3c94b98d-e540-467c-9a2f-717b1542d34a)

![image](https://github.com/botpress/v12/assets/14326057/ac3bd242-5162-4d13-8eb9-3442aab2fb4e)

![image](https://github.com/botpress/v12/assets/14326057/e4371c76-56af-4b03-8a0b-de67fee6c531)

![image](https://github.com/botpress/v12/assets/14326057/d801c5ed-6772-4c7f-af54-5659203b7e47)

![image](https://github.com/botpress/v12/assets/14326057/eb4e3c39-b1b2-4fb5-9325-e6e1691fb2e2)

![image](https://github.com/botpress/v12/assets/14326057/df5b61da-e80d-40c3-acd8-b6076f4250b3)

- OS: Ubuntu
- Botpress Version 12.31.0

**Comment by RqfaelJr** [comment]
You have to use triple "{" like this: {{{user.item_link}}}

**Comment by sebburon** [comment]
What @RqfaelJr said is correct
