### ISSUE TITLE
Accessing webchat URL parameters

### ISSUE THREAD

**Issue by epaminond** [botpress/v12#341]
When receiving event from webchat, that would be useful to have access to URL parameters, in order to customize answers or make redirects.

Example: calling mybot.com/s/chat?ref=some_flow_id will create a property ref: some_flow_id somewhere in user event, allowing to call bp.jumpTo(ref) server side
Example for facebook, it's http://m.me/mybot?ref=cinema

**Comment by camie-ace** [comment]
I'm building an onboarding chatbot, and I'm trying to store some variables as I send a user to the Botpress webchat

Is there a way to do that using URL parameters?

So I can just pre-fill the parameters from my Flutter app before sending the user to the bot
