### ISSUE TITLE
Ghost content sync fail

### ISSUE THREAD

**Issue by mhjb** [botpress/v12#457]
Make sure these checkboxes are checked before raising an issue, thank you!

- [x] Check that you are using node version >= `8.9`
- [x] Search the [documentation](https://botpress.io/docs)
- [x] Search the [help portal](https://help.botpress.io/)

Please also fill in these fields:

---

### Channels: Messenger, Slack, web

On production we have made changes to flows. As suggested in the version control tab, I run 

`./node_modules/.bin/botpress ghost-sync https://<<OUR APP>>.herokuapp.com`

I successfully login, and respond 'Yes' to the warning re. overwriting untracked/uncommitted local changes. 

```
[botpress] 	 ERR ENOENT: no such file or directory, open '<<PATH TO MY LOCAL INSTALL>>/generated/media/.ghost-revisions' while applying ghost content.
[botpress] 	 ERR Your content files may be in inconsistent state.
[botpress] 	 ERR It is recommended to reset the changes (like git reset) and try again.
```

What can you advise?

**Comment by AyushDey331** [comment]
[botpress] 	 ERR ENOENT: no such file or directory, open '<<PATH TO MY LOCAL INSTALL>>/generated/flows/skills/choice-89fc24.ui.json' while applying ghost content.
[botpress] 	 ERR Your content files may be in inconsistent state.
[botpress] 	 ERR It is recommended to reset the changes (like git reset) and try again.
