### ISSUE TITLE
Unable to install Botpress on Raspberry Pi using npm

### ISSUE THREAD

**Issue by shaundaws** [botpress/v12#486]
Hi, I'm trying to install botpress on a Raspberry pi using npm, but get the below error (running with or without sudo). I'm working through the installation page: 

https://botpress.io/docs/latest/getting_started/install/

And have tried a bunch of other changes, including those recommended on the npm help pages:

https://docs.npmjs.com/getting-started/fixing-npm-permissions 

Despite this, I'm getting the below error when I try to run the command:

`npm install -g botpress`

```
npm WARN engine botpress@10.48.5: wanted: {"node":">=8.9"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "botpress"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```

Any ideas?

-----------------------------------------------------------------------------------------

Make sure these checkboxes are checked before raising an issue, thank you!

- [x] Check that you are using node version >= `8.9`
- [x] Search the [documentation](https://botpress.io/docs)
- [x] Search the [help portal](https://help.botpress.io/)

Please also fill in these fields:

---

### Botpress version: `<<VERSION HERE>>`
N/A

### Channels: <<list of channels>>
N/A

**Comment by cmdaltctr** [comment]
did it work @shaundaws ?
