### ISSUE TITLE
My single choice response options disappear in the UI!! Help!

### ISSUE THREAD

**Issue by thenilaymodi** [botpress/v12#503]
Using Botpress 10.5 and web channel.

My response options to a single choice question disappear sometimes. It tends to happen after multiple page refreshes etc. In some cases it just start this way. Hard browser refreshes seem to be correlated with the response options disappearing. I have detailed my code setup below. 

I'm calling a proactive action. Inside my index.js I have this. It jumps to a Flow. 

```
bp.hear({ type: /proactive-trigger/i }, async (event, next) => {
      await bp.dialogEngine.jumpTo(event.sessionId || event.user.id, 'question.flow.json');
      await bp.dialogEngine.processMessage(event.sessionId || event.user.id, event);
      next();
 })
```

Inside the flow I'm just calling a custom action (actions.js) called askQuestion

```
async function askQuestion(state, event){
	
	const question = "Do you like it?";
	const choices = [
        {
          "title": "Yes",
          "value": "Yes"
        },
        {
          "title": "Sometimes",
          "value": "Sometimes"
        },
        {
          "title": "No",
          "value": "No"
        }
    ];

	await event.reply('#builtin_single-choice', { text: question, choices: choices, typing: true })
	
	return{
		...state
	}
}
```

Any ideas why this is happening? Is this a bug?

**Comment by JonnyClean** [comment]
test
