### ISSUE TITLE
Feature request : Allow the bot to send the first message

### ISSUE THREAD

**Issue by Bybeez** [botpress/v12#675]
Hello Botpress team,
While working on a bot, I was challenged by this.
When a user open the Webchat integration, it face a blank chatting interface which is not very user-friendly. It would be interesting to add the possibility for the bot to start the conversation.

 Please, consider to include this functionality into botpress.

**Comment by FujiwaraChoki** [comment]
They launched this feature. It's called **triggers**. You need to join the discord to request beta entry.

**Comment by mjannesary** [comment]
j

**Comment by mjannesary** [comment]
how can start conversation via bot in botpress v12
