### ISSUE TITLE
[FEATURE] channel-web: send events when smth is clicked

### ISSUE THREAD

**Issue by xavierbriole** [botpress/v12#750]
**Is your feature request related to a problem? Please describe.**
I tried with v12 but it's the same thing than v11. We can't listen events sent from an iframe when the bot is not hosted on the same server. I suggested a "sample" PR to fix it : botpress/botpress#1977 

I explain in deep the issue in this PR if you want more details

**Describe the solution you'd like**
postMessage events for some actions of bot :
`parent.postMessage({ name: 'openChatButton' }, '*')` => when openChatButton is clicked
`parent.postMessage({ name: 'closeChatButton' }, '*')` => when closeChatButton is clicked
etc..

**Comment by kunalgoyal9** [comment]
@xavierbriole @michaelmass 
I am looking for this functionality but can't find any.
How is botpress/v12 different from botpress/botpress ?
