### ISSUE TITLE
 redirect to an external url   using a button made in choice skill 

### ISSUE THREAD

**Issue by kenkaigu** [botpress/v12#786]
My feature request is to include an option on a button made from choice skill, to redirect a link to an external url...

Here's a detailed explanation including screenshots

https://help.botpress.io/t/how-to-redirect-to-an-external-url-while-using-a-button-made-in-choice-skill/1791

This option will be really beneficial  using choice skill buttons since at the moment, you can only add an external url if you are using cards...

**Comment by ragazzo-br** [comment]
I solved this problem, doing this: is enought add a simples text option and put an html external link as
 <a href="https://www.amazon.com">click to visit  Amazon</a>

**Comment by jondoescoding** [comment]
> <a href="https://www.amazon.com">click to visit

How did you manage to get this to work. Whenever I place the link within the standard node using text nothing happens.
