### ISSUE TITLE
V12.1.1 After upgrade to version 12.1.1 messages no longer working on Botpress server running on IIS 8.5 behind reverse proxy

### ISSUE THREAD

**Issue by lampyon-canada** [botpress/v12#797]
If I open any bot from the Studio (admin) and start the Emulator, messages are no longer reaching the bot server and messages from bot are also not reaching the emulator. Basically none of the bots will respond to anything.

I have just upgraded from 12.1.0 to 12.1.1 . 

I have the Botpress server on a Windows 2012 Sserver with IIS8.5 and reverse proxy set up. The same setup worked with 12.1.0 and stopped working with 12.1.1, without any changes in settings other than the upgrade itself from 12.1.0 to 12.1.1 .

If I log in to the webserver using remote desktop and open the Studio using http://localhost:3000 URL then the messages work in the emulator. So the issue would seem related to the reverse proxy - except for the fact that no settings were changed. For some reason what worked until version 12.1.0 no longer works under 12.1.1 . 

UPDATE: 
If I revert back to version 12.1.0 then messages work again, on the same webserver, same config.

**Comment by happyananth** [comment]
Thanks a lot for this document, this has helped me a lot.

could you please help me how I can enable the HTTPS for language server which is listening in port 3100 using URL re-write
