### ISSUE TITLE
Extracting a name from payload

### ISSUE THREAD

**Issue by alexmuchiri** [botpress/v12#869]
When sending a greeting, e.g. 
Bot: Hi I'm bot, what is your name?
User: My name is James
The bot typically responds with: pleasure to meet you my name is james

Evidently quite buggy... and also does not remember to CAP the name

**Comment by erenYaeger001** [comment]
Hey @EFF @alexmuchiri @aintHuman @michaelmass . I am facing the same challenge in my project. The solution above is on the same lines as I was thinking. But I am facing issue with how to store the username in a variable. I am 100% sure this isn't not the right way to do it, but can't find anything in the documentation or online.

It would be really helpful if either of you could suggest. Thanks!! 
<img width="728" alt="Screenshot 2023-12-27 at 12 16 40 AM" src="https://github.com/botpress/v12/assets/154908619/d67ba88e-33f8-4cb0-8fa7-3642e2939568">
