### ISSUE TITLE
An error occurred while executing the action "basic-skills/choice_parse_answer"

### ISSUE THREAD

**Issue by aintHuman** [botpress/v12#872]
Just upgraded from 12.2.1 to 12.2.3

Getting the following error in console.

<img width="1126" alt="Screen Shot 2019-11-27 at 12 00 14 pm" src="https://user-images.githubusercontent.com/49050968/69684683-ac3ac080-110d-11ea-889a-f4523cb52e43.png">

**Comment by AbdulmalekAI** [comment]
i have the same issues , 
Is there any solution
