### ISSUE TITLE
Wait for user input and then fall back after X time has elapsed

### ISSUE THREAD

**Issue by aintHuman** [botpress/v12#885]
I realise that timeout nodes can be created, and general timeout actions, etc..., but these all seem to be triggered after the global timeout setting has elapsed, and I already use this to trigger session timeout.

What would be great is if a node could wait for user input (ie type something), and then if the user does not provide after some short interval (much less than the global timeout setting, say 30 seconds vs the 5 minute global timeout), then the flow redirects to another node where say a single choice option could be presented to prompt the user what to do next.

**Comment by gabrielhmsantos** [comment]
I tried using the timeout, but apparently it is only triggered after the user types something due to "wait user input".
Could you show an example flow applying this request to return a message if the user does not respond in x seconds?

**Comment by gabrielhmsantos** [comment]
> Available in the latest releaase as a flow(create a flow called 'timeout'), hook (there is a hook type) and node (create a node called 'timeout')

I tried using the timeout, but apparently it is only triggered after the user types something due to "wait user input".
Could you show an example flow applying this request to return a message if the user does not respond in x seconds?
